### ISSUE TITLE
Issue with Sort Order (DG.AdvancedDataGridView 1.2.27307.7)

### ISSUE THREAD

**Issue by MattH-Work** [davidegironi/advanceddatagridview#93] opened 2022-09-08 15:02 UTC
As can be seen below, the 'Days Remaining' column does not sort correctly
It is detected as numerical, as the sort order offers up 'Smallest to Largest' etc
All other columns sort correctl;y (Text, Dates & two other numerical)
![image](https://user-images.githubusercontent.com/84494183/189156250-635f3469-d16d-45c2-9e73-ab5afb68fbbb.png)

**Comment by davidegironi** [comment] 2022-09-08 15:29
Hello, it seems it is a string column. Is should be a int column type.
Take a look at the sample project, there you can find an "int" column ordered. Lokking at the code you will find type int for this column
`_dataTable.Columns.Add("int", typeof(int));`

**Comment by davidegironi** [comment] 2022-09-13 12:32
I was not able to reproduce the error. I close this issue.

**Closed** 2022-09-13 12:32 UTC
